version: 2
jobs:
  build:
    docker:
        - image: alekseikharlamovsisu/pe2pectf:20190901

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v -mod vendor ./...
      - run: ./integration-tests/run.sh

