version: 2
jobs:
    build:
        docker:
            - image: alekseikharlamovsisu/pe2pectf:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
        - checkout
        - run: ./integration-tests/run.sh
